AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
    Default: dev
  
Mappings:
  dev:
    DeploymentConfig:
      Location: us-west1
      Environment: dev
  prod:
     DeploymentConfig:
      Location: us-west2
      Environment: prod 

Globals:
  Function:
    Runtime: python3.11
    Environment:
      Variables:
        LOCATION: ${{Mappings.dev.DeploymentConfig.Location}}
        ENV: ${{Mappings.dev.DeploymentConfig.Environment}}

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda_handler.lambda_handler
      Environment:
        Variables:
          ENV_VAR: ENV_VAR